### ISSUE TITLE
Eliminate color-namedColors.js in favor of DOM based solution?

### ISSUE THREAD

**Issue by bebraw** [One-com/one-color#19]
Hi,

It looks like it might be possible to eliminate the lookup you have at color-namedColors.js by calculating the color via DOM. You simply have to create a dummy element and set its CSS color with the given name. After that you can fetch the real value.

I'm not sure how well this works cross-browser. In case you are interested in slimming down the library, I guess this is something you might want to investigate.

**Comment by Munter** [comment]
I'm closing this. I don't really feel for adding dom interaction into the mix. The size overhead is minimal compared to possible unforeseen side effects of messing with dom

**Comment by bebraw** [comment]
Sure.
