### ISSUE TITLE
New function doen't works for chrome apps

### ISSUE THREAD

**Issue by blackrabbit99** [One-com/one-color#22]
Is the any way to support your lib without new function?

**Comment by SlexAxton** [comment]
Is it possible to generate the library as part of a release? Would love to keep atom/native support for css-colorguard things.

**Comment by Munter** [comment]
We will give rewriting the library a shot on monday. Hopefully we can remove the runtime generation that requires eval. We expect the size of the library to grow because of it though, and it will be a major version increase since this also means dropping the original goal of being a micro lib

**Comment by Munter** [comment]
This should be fixed in v3.0.0
