### ISSUE TITLE
Unnamed AMD module

### ISSUE THREAD

**Issue by sir-dunxalot** [One-com/one-color#26]
The AMD module defined in `color.js` is unnamed:

```js
define(function () {
    return ONECOLOR;
});
```

However, this makes AMD loading incompatible with tools like Ember CLI. For example, [this issue] (https://github.com/ember-cli/ember-cli/issues/770). I understand there are some benefits to an unnamed module because you can use it anywhere under different names. However, would you be open to using a named module or allowing the developer to set the module name somewhere? In either case, the production code would resemble something like:

```js
define('one-color', [], function () {
    return ONECOLOR;
});
```

**Comment by papandreou** [comment]
That'll actually break more things than it'll fix, as that syntax is only intended to be used in the output of an optimizer tool. See the reasoning here: [require.js api docs](http://requirejs.org/docs/api.html#modulename):

**Comment by Munter** [comment]
I would open a bug on Ember CLI to get this fixed. They are not following the specification as far as I know
