### ISSUE TITLE
new Function() error in atom

### ISSUE THREAD

**Issue by zhouwenbin** [One-com/one-color#28]
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

**Comment by papandreou** [comment]
Duplicate of https://github.com/One-com/one-color/issues/22
