### ISSUE TITLE
About the source map files

### ISSUE THREAD

**Issue by x09326** [One-com/one-color#32]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).
But I meet some problems.

I send a pull request to cdnjs. https://github.com/cdnjs/cdnjs/pull/7878
But the map files (```one-color-all.map``` and ```one-color.map```) look strange.
Can you explain or check it?
Because I don't know very much about js and map file.
I hope I can learn some information from here, and send the pull request successfully.

Thank you.

**Comment by papandreou** [comment]
Fixed in 3.0.2. Thanks for reporting :)

**Comment by PeterDaveHello** [comment]
@x09326 you should close this now.
