### ISSUE TITLE
Module not found: Error: Can't resolve 'ONECOLOR'

### ISSUE THREAD

**Issue by oshihirii** [One-com/one-color#41]
Hello,

I posted this issue over on [colorjoe](https://github.com/bebraw/colorjoe/issues/46) but it seems to be a bit quiet over there.  

Steps to reproduce:

**my_entry_file.js:**

```
import onecolor from './one-color';
import colorjoe from './colorjoe';
```

**webpack.config.js**

```
entry: "./src/js/my_entry_file.js",
output: {
filename: "bundle.js",
path: path.resolve(__dirname, "dist/js")
},
```

When running webpack, I get error:

```
ERROR in ./src/js/colorjoe.js
Module not found: Error: Can't resolve 'ONECOLOR' in 'C:\Users\Me\Documents\my_repo\src\js'
 @ ./src/js/colorjoe.js 9:8-11:10
```

The relevant files used are:

https://github.com/One-com/one-color/blob/master/one-color.js

https://github.com/bebraw/colorjoe/blob/master/dist/colorjoe.js

[ Note:  later in this thread I switched to using the files in the colorjoe `/src` folder ]

**Comment by papandreou** [comment]
At a quick glance it looks like the error happens in https://github.com/bebraw/colorjoe/blob/12820d0eb0b81bbe807b435f93c09414a33cc6f7/dist/colorjoe.js#L5 -- it appears to be a hand-rolled, not quite standard UMD wrapper.

I think it would have a better at working if it tried CommonJS first. Could you try to hand-edit dist/colorjoe.js and swap the `if (typeof define === 'function' && define.amd)` and `else if (typeof module === 'object' && module.exports)` around so it looks like this?

```js
(function (root, factory) {
  if (root === undefined && window !== undefined) root = window;
  if (typeof module === 'object' && module.exports) {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory(require("onecolor"));
  } else if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module unless amdModuleId is set
    define(["ONECOLOR"], function (a0) {
      return (root['colorjoe'] = factory(a0));
    });
  } else {
    root['colorjoe'] = factory(root["one.color"]);
  }
}(this, function (ONECOLOR) {
```

If that does work, I think we should try to upstream that change to colorjoe. If it doesn't I'll try to dig in and figure out what's wrong :)

**Comment by oshihirii** [comment]
Thank you, unfortunately that change gives these errors:

> ERROR in ./src/js/colorjoe.js
> Module not found: Error: Can't resolve 'ONECOLOR' in 'C:\Users\Me\Documents\my_repo\src\js'
>  @ ./src/js/colorjoe.js 14:8-16:10
>  @ ./src/js/common.js
> 
> ERROR in ./src/js/colorjoe.js
> Module not found: Error: Can't resolve 'onecolor' in 'C:\Users\Me\Documents\my_repo\src\js'
>  @ ./src/js/colorjoe.js 11:33-52
>  @ ./src/js/common.js

However, on colorjoe's `Readme`:

https://github.com/bebraw/colorjoe#installation

It says:

> Add prepackaged `dist/colorjoe.js` and `css/colorjoe.css` to your page or use AMD to load the dependencies from `src/`.
> 
> Note that you need to load [one.color](https://github.com/One-com/one-color) before using `colorjoe`. In case you are using RequireJS, shim it at your configuration so that it is bound to `onecolor`.


So if I use the file from `/src`:

https://github.com/bebraw/colorjoe/blob/master/src/colorjoe.js

instead of the file from `/dist`:

https://github.com/bebraw/colorjoe/blob/master/dist/colorjoe.js

There are no errors in the webpack build, however I get this error in chrome devtools on front end:

> Uncaught ReferenceError: extras is not defined
>     at eval (webpack:///./src/js/colorjoe.js?:75)  

If I try to import the extras file from the colorjoe `/src` folder:

https://github.com/bebraw/colorjoe/tree/master/src

And `import` statements are defined like this in `my_entry_file.js`:

```
import extras from './extras';
import onecolor from './one-color';
import colorjoe from './colorjoe';
```

the frontend error remains the same:

> Uncaught ReferenceError: extras is not defined
>     at eval (webpack:///./src/js/colorjoe.js?:75)

**Comment by Munter** [comment]
Looks like Colorjoe could use a little update to use js modules and package its dist files with rollup or whatever: https://github.com/bebraw/colorjoe/blob/master/src/colorjoe.js#L19
That's a dependency on `one-color` being available in the global scope as `ONECOLOR`, which `one-color` doesn't do by itself.

I'm not quite sure why your imports are apparently using the AMD path either, or why they are using the `dist`-files. I'd expect the raw sources to be used

**Comment by oshihirii** [comment]
I'm stumped myself and not sure how to proceed.

I'm assuming there is something I am not doing correctly in the import process, as I think the `colorjoe` developer is a `webpack` core developer, and therefore also assume his libraries are optimised for the `webpack` process.

**Comment by oshihirii** [comment]
For reference, as mentioned in the comment above, https://github.com/One-com/one-color/issues/41#issuecomment-392462997, the build is working with files from `/src` but then I get errors on the frontend unfortunately.

**Comment by oshihirii** [comment]
I have used the files from `/src` folder, and the build completes, but then I get this on frontend:

> Uncaught ReferenceError: extras is not defined
> at eval (webpack:///./src/js/colorjoe.js?:75)

My entry file imports `colorjoe` like this:

```
import extras from './extras';
import onecolor from './one-color';
import colorjoe from './colorjoe';
```

If this is not the correct way to do it, can anyone please tell me the correct way to do it?

**Comment by oshihirii** [comment]
Any updates on this?  

I'd love to be able to include `colorjoe` in webpack build process.  

Thanks.

**Comment by bebraw** [comment]
@oshihirii I'm a bit swamped with work at the moment. The best you could do is to rewrite the build process of colorjoe (use rollup or so) and PR. 👍

**Comment by oshihirii** [comment]
Ok, for reference, I don't know how to do that (i had a quick look around `colorjoe.js`, but it's beyond my skills).  

Perhaps someone else who sees this thread might have those skills.

**Comment by Munter** [comment]
We've been through a similar conversion in this library as well. Here is some inspiration:

**Replacing custom build system with a `require()` based dependency graph + browserify**
https://github.com/One-com/one-color/commit/57c931f5338dbd1e44c5dcefaa88bf752afc8b17

**Replacing browserify with rollup**
https://github.com/One-com/one-color/commit/dd5b3cbda0ab563678ee71f900c3e721f2b6e7a2

**Comment by papandreou** [comment]
Colorjoe 4 is out now with a fix for this problem. Closing :)
